### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by AviFix** [song940/node-gsm#9]
Hi

I get this error

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at Object.inherits (node:util:251:11)
    at Object.<anonymous> (/home/pi/sms/node_modules/gsm2/modem.js:78:6)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/pi/sms/node_modules/gsm2/sms.js:1:15) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Thanks

**Comment by AviFix** [comment]
Solved by [PR11](https://github.com/song940/node-gsm/pull/11)
